server:
  port: 9001

spring:
  application:
    name: gateway
  security:
    user:
      name: constanline
      password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 20
        max-wait: 3000
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
        add-to-simple-url-handler-mapping: true
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: book-route
          uri: lb://book-service
          predicates:
            - Path=/book/**
          filters:
            # 降级配置
            - name: CircuitBreaker
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            # 限流配置
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@hostNameKeyResolver}"

        - id: account-route
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            # 降级配置
            - name: CircuitBreaker
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            # 限流配置
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@hostNameKeyResolver}"
      default-filters:
        - StripPrefix=1
#        - SaveSession
  session:
    store-type: redis

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    service-url:
      defaultZone: http://localhost:9002/eureka/

#logging:
#  level:
#    org.springframework.security: debug
