server:
  port: 9002

spring:
  application:
    name: spring-cloud-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:9002/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0