server:
  port: 9003

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cloud_account?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-test-query: select 1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9002/eureka/
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
          - mapping

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl